apiVersion: extensions/v1beta1
kind: Ingress
metadata:
	namespace: default
	name: traefik
	annotations:
		kubernetes.io/ingress.class: "traefik"
spec:
	rules:
		- host: traefik.archifleks.net
			http:
				paths:
					- backend:
						serviceName: traefik-console
						servicePort: 8080
